apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: example-analysis
spec:
  metrics:
  - name: success-rate
    # NOTE: prometheus queries return results in the form of a vector.
    # So it is common to access the index 0 of the returned array to obtain the value
    successCondition: result[0] < 100
    count: 3
    failureLimit: 1
    interval: 1m
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitor.svc.cluster.local.:9090
        query: |
          sum(traefik_service_requests_total)
